# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
%define ver_maj 4
%define ver_min 1
%define ver_pat 18
# << macros

Name:       kcalcore
Summary:    Extended KDE kcal calendar library port for Maemo
Version:    %{ver_maj}.%{ver_min}.%{ver_pat}
Release:    1
Group:      System/Libraries
License:    LGPLv2
Source0:    %{name}-%{version}.tar.gz
Source100:  kcalcore.yaml
Patch0:     use_connman_clock.patch
Patch1:     fix_timezone_fallback.patch
Patch2:     raweventsfordate_event_duplication.patch
Patch3:     memorycal_delete_incidence_fix.patch
Patch4:     build_with_gcc4.6.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtDBus)
BuildRequires:  pkgconfig(libical)
BuildRequires:  pkgconfig(sqlite3)
BuildRequires:  pkgconfig(uuid)
BuildRequires:  doxygen
BuildRequires:  fdupes


%description
%{summary}.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# use_connman_clock.patch
%patch0 -p1
# fix_timezone_fallback.patch
%patch1 -p1
# raweventsfordate_event_duplication.patch
%patch2 -p1
# memorycal_delete_incidence_fix.patch
%patch3 -p1
# build_with_gcc4.6.patch
%patch4 -p1
# >> setup
# << setup

%build
# >> build pre
touch src/libkcalcoren.so.%{ver_maj}.%{ver_min}.%{ver_pat}
%qmake DEFINES=USE_ICAL_0_46
make VER_MAJ=%{ver_maj} VER_MIN=%{ver_min} VER_PAT=%{ver_pat} %{?_smp_mflags}
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
%qmake_install VER_MAJ=%{ver_maj} VER_MIN=%{ver_min} VER_PAT=%{ver_pat}
%fdupes %{buildroot}%{_includedir}/
%fdupes %{buildroot}%{_docdir}/libkcalcoren-doc/
ln -s libkcalcoren.so.%{ver_maj}.%{ver_min}.%{ver_pat} %{buildroot}%{_libdir}/libkcalcoren.so
ln -s libkcalcoren.so.%{ver_maj}.%{ver_min}.%{ver_pat} %{buildroot}%{_libdir}/libkcalcoren.so.%{ver_maj}
ln -s libkcalcoren.so.%{ver_maj}.%{ver_min}.%{ver_pat} %{buildroot}%{_libdir}/libkcalcoren.so.%{ver_maj}.%{ver_min}
chmod +x %{buildroot}/%{_libdir}/libkcalcoren.so.%{ver_maj}.%{ver_min}.%{ver_pat}
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%defattr(644,root,root,-)
%{_libdir}/libkcalcoren.so.*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libkcalcoren.so
%{_includedir}/kcalcoren/*.h
%{_includedir}/kcalcoren/K*
%{_includedir}/kcalcoren/kpimutils/*.h
%{_libdir}/pkgconfig/libkcalcoren.pc
%{_datadir}/qt4/mkspecs/features/kcalcoren.prf
# << files devel

